### ISSUE TITLE
Maintainer is switching to GitLab

### ISSUE THREAD

**Issue by drj11** [conda-forge/pypng-feedstock#1]
### Comment:

Hi, i am the maintainer of the PyPNG package. I don't really do conda or conda-forge. However

- i am moving development to GitLab https://gitlab.com/drj11/pypng
- i am considering not using PyPI for future releases.

So, how do you feel about drawing sources from GitLab?

A gentle start would be to bump to PyPNG 0.0.21 (release August 2021). I'm happy to submit a PR, if you're happy to provide a bit of guidance.

**Comment by hmaarrfk** [comment]
Please edit this line of code accordingly in a PR
https://github.com/conda-forge/pypng-feedstock/blob/main/recipe/meta.yaml#L9

**Comment by hmaarrfk** [comment]
There is also a way to change the version at the top of same file
